### ISSUE TITLE
اجرا نشدن برنامه در پایتون

### ISSUE THREAD

**Issue by goodosuser** [balemessenger/bale-bot-python#4]
سلام
python3 test.py 
چنین خطایی مشاهده می شود.
لطفا راهنمایی کنید

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from balebot.updater import Updater
  File "/usr/local/lib/python3.5/dist-packages/balebot/updater.py", line 4, in <module>
    from balebot.dispatcher import Dispatcher
  File "/usr/local/lib/python3.5/dist-packages/balebot/dispatcher.py", line 7, in <module>
    from balebot.bot import Bot
  File "/usr/local/lib/python3.5/dist-packages/balebot/bot.py", line 3, in <module>
    import aiohttp
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/__init__.py", line 5, in <module>
    from . import hdrs  # noqa
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/hdrs.py", line 2, in <module>
    from multidict import istr
  File "/usr/local/lib/python3.5/dist-packages/multidict/__init__.py", line 18, in <module>
    from ._abc import MultiMapping, MutableMultiMapping
  File "/usr/local/lib/python3.5/dist-packages/multidict/_abc.py", line 37, in <module>
    class MutableMultiMapping(MultiMapping[_T], MutableMapping[str, _T]):
  File "/usr/local/lib/python3.5/dist-packages/multidict/_abc.py", line 44, in MutableMultiMapping
    def extend(self, *args: _Arg[_T], **kwargs: _T) -> None:
  File "/usr/lib/python3.5/typing.py", line 546, in __getitem__
    "Cannot subscript an existing Union. Use Union[u, t] instead.")
TypeError: Cannot subscript an existing Union. Use Union[u, t] instead.

**Comment by baleadmin** [comment]
شما در فرایند نصب نیازمندی ها با مشکل مواجه شدید
باید دوباره برای نصب
dependency 
تلاش کنید

**Comment by goodosuser** [comment]
> شما در فرایند نصب نیازمندی ها با مشکل مواجه شدید
> باید دوباره برای نصب
> dependency
> تلاش کنید

اگه ممکنه دقیق تر راهنمایی کنید- مشکلی به نظر مشاهده نمی شده 

توی سایت هم گفته شده
pip
اما
pip3.5
درسته به نظرم

"Cannot subscript an existing Union. Use Union[u, t] instead.")
TypeError: Cannot subscript an existing Union. Use Union[u, t] instead.

**Comment by baleadmin** [comment]
بهتر است که یک 
virtual environment 
برای 
interpreter 
خود بسازید و به وسیله دستور
pip
نیازمندی ها را دانلود کنید
